platform :ios,’8.0'
target 'DrivieSchoolStudents' do
    pod 'AFNetworking'   
    pod 'SDWebImage'
    pod 'SDCycleScrollView'
    pod 'IQKeyboardManager'
    pod 'MJExtension'
    pod 'SVProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'BlocksKit'
    pod 'MOFSPickerManager'
    pod 'GLViewPagerViewController'
    pod 'UITextView+Placeholder'
    pod 'TZImagePickerController', '~> 2.1.4'
end

