platform :ios,’8.0'
target 'DrivieSchoolStudents' do
    pod 'AFNetworking'   
    pod 'SDWebImage'
    pod 'SDCycleScrollView'
    pod 'IQKeyboardManager'
    pod 'MJExtension'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'BlocksKit'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MOFSPickerManager'
    pod 'UITextView+Placeholder'
    pod 'TZImagePickerController', '~> 2.1.4'
    pod 'FMDB'
    pod 'YYCache'
    pod 'SVProgressHUD'
    pod 'BaiduMapKit' #百度地图SDK
	
	pod 'UMCCommon'
  pod 'UMCAnalytics'
	# 集成微信(完整版14.4M)
	pod 'UMCShare/Social/WeChat'
	# 集成QQ/QZone/TIM(完整版7.6M)
	pod 'UMCShare/Social/QQ'
	# 集成新浪微博(完整版25.3M)
	pod 'UMCShare/Social/Sina'
end

